---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddrafts: false
indexes:
  category: "categories"
  archive: "archives"
baseurl: "http://danielsjourney.com/"
title: "Daniel Miller"
permalinks:
  blog: /blog/archives/:year/:month/:day/:slug
  archive: /blog/archives/
...